name: auto-assign
on:
  pull_request: 
    types: [opened, reopened]

jobs:
  reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: ugns/actions/github/auto-assign@1.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: '.github/auto-assign.yml'
